AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for serverless-cms-dotnet

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

# Parameters:
  # CognitoUserEmail:
  #   Description: Email address of the created user
  #   Type: String
  # APIStageName:
  #   Default: api
  #   Description: StageName of API Gateway deployment
  #   Type: String

Resources:
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: "Serverless CMS Authentication Client"
      GenerateSecret: true
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        AccessToken: "minutes"
        IdToken: "minutes"
        RefreshToken: "days"
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs: 
        - "http://localhost:3000/api/auth/callback/cognito"
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - profile
        - openid
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: true
      EnablePropagateAdditionalUserContextData: false
      AuthSessionValidity: 3
  
  # UserPoolUser:
  #   Type: AWS::Cognito::UserPoolUser
  #   Properties:
  #     DesiredDeliveryMediums:
  #       - EMAIL
  #     Username: !Ref CognitoUserEmail
  #     UserPoolId: !Ref UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain : "serverless-cms-user-pool"
      UserPoolId : !Ref UserPool

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: Severless CMS User Pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      MfaConfiguration: "OFF"
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameConfiguration:
        CaseSensitive: false

  # AccessLogGroup:
  #   Type: AWS::Logs::LogGroup

  HelloWorldApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Hello World API Gateway
      StageName: Staging
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'

  GenPresignedUrlGateway:
    # DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: GenPresignedUrlGateway Api Gateway
      StageName: Staging
      Cors: "'*'"
      Auth:
        Authorizers:
            CognitoAuthorizer:
              UserPoolArn: !GetAtt "UserPool.Arn"
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'

  FetchTableContentGateway:
    # DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: FetchTableContent Api Gateway
      StageName: Staging
      Cors:
            AllowMethods: "'GET,POST,OPTIONS'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
      # Auth:
      #   Authorizers:
      #       CognitoAuthorizer:
      #         UserPoolArn: !GetAtt "UserPool.Arn"
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'

  CreateTableApiGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: Create Table API Gateway
      StageName: Staging
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'


  GetGroupsGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: Get Groups API Gateway
      StageName: Staging
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'



  AddGroupGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: Add Group To Post List API Gateway
      StageName: Staging
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
      AccessLogSetting:
        # DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApiGateway
            Path: /hello
            Method: GET

  CreateTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/CreateTable/
      Handler: CreateTable::CreateTable.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Timeout: 120
      Role: null
      Policies:
        - Statement:
          - Sid: DynamoDBFullAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: '*'
      Events:
        CreateTableApi:
          Type: Api
          Properties:
            RestApiId: !Ref CreateTableApiGateway
            Path: /create-table
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GenPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/GenPresignedUrl/
      Handler: GenPresignedUrl::GenPresignedUrl.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Events:
        GenPresignedUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref GenPresignedUrlGateway
            Path: /gen-presigned-url
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  
  GetGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/GetGroups/
      Handler: GetGroups::GetGroups.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Role: null
      Policies:
        - Statement:
          - Sid: DynamoDBFullAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: '*'
      Events:
        GetGroupsApi:
          Type: Api
          Properties:
            RestApiId: !Ref GetGroupsGateway
            Path: /get-groups
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  
  FetchTableContentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/FetchTableContent/
      Handler: FetchTableContent::FetchTableContent.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Role: null
      Policies:
        - Statement:
          - Sid: DynamoDBFullAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: '*'
      Events:
        FetchTableContentApi:
          Type: Api
          Properties:
            RestApiId: !Ref FetchTableContentGateway
            Path: /fetch-table-content
            Method: GET
            # Auth:
            #   Authorizer: CognitoAuthorizer

  AddGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/AddGroup/
      Handler: AddGroup::AddGroup.Function::FunctionHandler
      Runtime: dotnet8
      Architectures:
      - x86_64
      Role: null
      Timeout: 120
      Policies:
        - Statement:
          - Sid: DynamoDBFullAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: '*'
      Events:
        AddGroupApi:
          Type: Api
          Properties:
            RestApiId: !Ref AddGroupGateway
            Path: /add-group-to-post-list
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  readingListDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: readingList
      AttributeDefinitions:
        - AttributeName: "ItemId"
          AttributeType: "S"
        - AttributeName: "Title"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ItemId"
          KeyType: "HASH"
        - AttributeName: "Title"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  postDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: postList
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "myGSI"
          KeySchema: 
            - 
              AttributeName: "SK"
              KeyType: "HASH"
          Projection: 
            NonKeyAttributes: 
              - "data"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"